### ISSUE TITLE
Acessing request and container instances from route

### ISSUE THREAD

**Issue by randohinn** [mattstauffer/Torch#65]
@mattstauffer Hey. Given the routing index.php example in the master branch. I do something like this

```
 $configPath = __DIR__ . '/../config/';
    
    $array = [
        'site' => require $configPath . 'site.php',
        'db' => require $configPath . 'database.php'
    ];
    
    $config = new Config($array);

    // Create a service container
    $container = new Container;

    $request = Request::capture();
    
    $container->instance('Illuminate\Http\Request', $request);
    $container->instance('config', $config);
```

After which, routes.php is required into the app. 
```
<?php
    use Illuminate\Routing\Router;

    $router->get('/', function () {
        return $config->get('site.setup');
    });
```
How could I access the config in here?

**Comment by AkenRoberts** [comment]
Just use the `$config` variable as if it was already defined in routes.php. Just like `$router` is instantiated in index.php, then used in routes.php without redefining it.

**Comment by randohinn** [comment]
@AkenRoberts that'd be a negative.

```
Notice: Undefined variable: config in C:\Users\rando\Documents\Webdev\cmsdev\public\routes.php on line 5

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in C:\Users\rando\Documents\Webdev\cmsdev\public\routes.php:5 Stack trace: #0 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\routing\Route.php(198): {closure}() #1 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\routing\Route.php(172): Illuminate\Routing\Route->runCallable() #2 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\routing\Router.php(659): Illuminate\Routing\Route->run() #3 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #4 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #5 C:\Users\rando\Documents\Webdev\cmsdev\vendor\illuminate\routing\Router.php(661): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #6 C:\Users\rando in C:\Users\rando\Documents\Webdev\cmsdev\public\routes.php on line 5
```

**Comment by AkenRoberts** [comment]
Since you're in a Closure, you'll have to import the variable via `use`:

    function () use ($config) {
        // ...
    }

**Comment by randohinn** [comment]
@AkenRoberts That works, thanks. What about in `$router->get('/serve', 'App\Controllers\CoreController@serve');` ? How to use it in the serve? Preferrably automagically

**Comment by AkenRoberts** [comment]
The Router will use the Container to perform constructor dependency injection, just like you would in Laravel. So you have a couple options:

1) Bind Config to the container using a fully-qualified class name, then typehint it in your controller.

```php
// Bootstrap
$config = new Config($array);
$container->instance(Config::class, $config);

// Controller
class CoreController
{
    private $config;

    public function __construct(Config $config)
    {
        $this->config = $config;
    }

    // ...
}
```

You can also use `$container->alias()` to alias the FQCN to the `"config"` string already bound.

2) Tell the Container how to create the controller. Using the same `CoreController` above with the typehinted Config class, add this to your bootstrap process:

```php
$container->bind(CoreController::class, function (Container $container) {
    return new CoreController($container->make('config'));
});
```

**Comment by randohinn** [comment]
Works, thanks. If the typehint could dissapear, that'd be even more 💲 💲 💲 .

**Comment by AkenRoberts** [comment]
Sure thing.
